name: the_designer_chowk
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_switch: ^0.3.2
  pin_code_fields: ^7.4.0
  contained_tab_bar_view: ^0.8.0
  like_button: ^2.0.4
  language_builder: ^0.1.2
  http: ^0.13.4
  motion_toast: ^2.3.0
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  image_cropper: ^2.0.3
  flutter_bounceable: ^1.0.2
  get: 4.6.5
  flutter_launcher_icons: 0.10.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/designer-chowk-logo_eng.png'

flutter:
  uses-material-design: true
  assets: 
    - assets/images/designer-chowk-logo_eng.png
    - assets/images/image.png
    - assets/images/edit.png
    - assets/images/picture.png
    - assets/images/sign-out-alt.png
    - assets/images/arrow_right.png
    - assets/images/notifications.png
    - assets/images/edit_pen.png
    - assets/images/back_photo_english.png
    - assets/images/back_photo_hindi.png
    - assets/images/image_blog.png
    - assets/images/rectangle_front.png
  fonts:
    - family: GilroyBold
      fonts: 
        - asset: fonts/Gilroy-Bold.ttf
          weight: 700
    - family: GilroySemiBold
      fonts: 
        - asset: fonts/Gilroy-SemiBold.ttf
          weight: 600
    - family: GilroyMedium
      fonts: 
        - asset: fonts/Gilroy-Medium.ttf
          weight: 500
    - family: GilroyRegular
      fonts: 
        - asset: fonts/Gilroy-Regular.ttf
          weight: 400
    - family: GilroyLight
      fonts: 
        - asset: fonts/Gilroy-Light.ttf
          weight: 200

